name: VPS Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: VPS Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ahmedmagdy-api-vocavault/htdocs/api.vocavault.ahmedmagdy.cloud
            git fetch origin
            git reset --hard origin/main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan optimize
            sleep 5
            curl -f https://api.vocavault.ahmedmagdy.cloud
