name: Deploy

run-name: Deploy - ${{ github.event.workflow_run.head_commit.message }}

permissions:
  contents: read

on:
  workflow_run:
    workflows:
      - Check
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    environment:
      name: Production
      url: https://api.vocavault.ahmedmagdy.cloud

    steps:
      - name: VPS Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ahmedmagdy-api-vocavault/htdocs/api.vocavault.ahmedmagdy.cloud

            git fetch origin
            git reset --hard origin/main

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force

            php artisan optimize

            sleep 5

            curl -f https://api.vocavault.ahmedmagdy.cloud
